// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var total = 0;

var a = 1;
var b = 2;
var temp;

while (b < 4000000) {
  if (b % 2 === 0) {
    total += b;
  }
  temp = b;
  b += a;
  a = temp;
}

console.log(total);

// Congratulations, the answer you gave to problem 2 is correct.

// You are the 355711th person to have solved this problem.
